name: Test
on:
  pull_request:
  push:
    branches:
      - master
      - develop
    
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
      
      - name: Install npm packages
        run: npm ci

      - name: Test by vitest
        run: npm run test
